application/application/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	url(r'^', include('form.urls')),
    url(r'^admin/', include(admin.site.urls)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

application/form/urls.py
from django.conf.urls import url
from form import views

urlpatterns = [
	# url(r'^project/(?P<url>[a-z 0-9 \. \/]+)$', views.project_edit),
	url(r'^$',views.home),
	url(r'success/$',views.success)
]

application/form/models.py
from django.db import models
from django.conf import settings
import os, datetime
from django.template.defaultfilters import slugify
from form.GDriveConnect import *
from django.core.mail import send_mail
from django.core.mail import EmailMessage


class UploadedFile(models.Model):
	def location(self,title):
		title = title.rsplit(".",1)
		fileName = "%s.%s"%(slugify(title[0]),title[1])
		self.extention = ".%s"%title[1]
		return fileName
		return "location.pdf"
	
	theFile = models.FileField(upload_to=location,blank=True)#"",blank=True)#	
	extention = models.CharField(max_length=30,blank=True)

	def __unicode__(self):
		return "%s"%(str(self.theFile))
	

class Application(models.Model):
	slug = models.SlugField(blank=True)
	fileName = models.SlugField(blank=True)
	uploaded = models.DateTimeField(auto_now=True)

	fellowship = models.CharField(max_length=500)

	fullName = models.CharField(max_length=500)
	email = models.CharField(max_length=500)
	phone = models.CharField(max_length=500)

	# statement = models.TextField(max_length=1000)

	cv =  models.ForeignKey(UploadedFile,related_name="cv")
	portrait = models.ForeignKey(UploadedFile,related_name="portrait")
	reference_1 = models.ForeignKey(UploadedFile,related_name="reference_1")
	reference_2 = models.ForeignKey(UploadedFile,related_name="reference_2")
	reference_3 = models.ForeignKey(UploadedFile,related_name="reference_3")
	letter_of_intent = models.ForeignKey(UploadedFile,related_name="letter_of_intent")

	def __unicode__(self):
		return "%s %s"%(self.fullName,self.uploaded)
	
	def save(self,*args, **kwargs):
		service = getService()
		slug = slugify(self.fullName)
		dateString = datetime.datetime.now().strftime("%y-%m-%d-%H-%M")

		
		folder = createFolder(service, "%s-%s-%s"%(slug, dateString,self.fellowship))["id"]
		formData(service,slug,dateString,self,folder)
		upLoadToGD(service, self.cv, folder, "cv.pdf", "application/pdf")
		upLoadToGD(service, self.portrait, folder, "portrait.jpg", "image/jpeg")
		upLoadToGD(service, self.reference_1, folder, "reference1.pdf", "application/pdf")
		upLoadToGD(service, self.reference_2, folder, "reference2.pdf", "application/pdf")
		upLoadToGD(service, self.reference_3, folder, "reference3.pdf", "application/pdf")
		upLoadToGD(service, self.letter_of_intent, folder, "letter_of_intent.pdf", "application/pdf")


		title = "%s submitted"%self.fullName
		message = """
				Hello!
				%s has submitted their completed fellowship application. 
				View their application at: https://drive.google.com/drive/u/0/folders/%s
				OR 
				view all available applications at: https://drive.google.com/drive/u/0/folders/0BxArj8ptnN7AXzJ5WEdrZUZQLVU
				+ + + 
				For technical issues, please contact: collaborate@alsocollective.com
			"""%(self.fullName,folder)
		messageHTML = """
				Hello!<br><br> 
				%s has submitted their completed fellowship application.<br><br>
				View their application at: <a href='https://drive.google.com/drive/u/0/folders/%s'> https://drive.google.com/drive/u/0/folders/%s </a><br><br>
				OR<br><br>
				view all available applications at: <a href='https://drive.google.com/drive/u/0/folders/0BxArj8ptnN7AXzJ5WEdrZUZQLVU'> https://drive.google.com/drive/u/0/folders/0BxArj8ptnN7AXzJ5WEdrZUZQLVU </a><br><br>
				+ + + <br><br>
				For technical issues, please contact: <a href='mailto:collaborate@alsocollective.com'>collaborate@alsocollective.com</a><br><br>
			"""%(self.fullName,folder,folder)
		send_mail(title,message,"orthosickkids@gmail.com" ,[settings.SHARE_WITH_THIS_USER], fail_silently=False, html_message=messageHTML)
		
		super(Application, self).save(*args, **kwargs)

application/form/forms.py
from django.forms import ModelForm
from django import forms
from form.models import *


class ExtFileField(forms.FileField):
	def __init__(self, *args, **kwargs):
		ext_whitelist = kwargs.pop("ext_whitelist")
		self.ext_whitelist = [i.lower() for i in ext_whitelist]

		super(ExtFileField, self).__init__(*args, **kwargs)

	def clean(self, *args, **kwargs):
		print self
		data = super(ExtFileField, self).clean(*args, **kwargs)
		if data:
			filename = data.name
			# print self
			ext = os.path.splitext(filename)
			ext = ext[1]
			ext = ext.lower()
			if ext not in self.ext_whitelist:
				raise forms.ValidationError("Filetype '%s' is not allowed for this field." % ext)
			elif (data._size > settings.MAX_UPLOAD_SIZE):
				raise forms.ValidationError("File is too large %s"%data._size)

		elif not data and self.required:
			raise forms.ValidationError("Required file not found for %s" % self.label)
		return data
		
class UploadForm(ModelForm):
	def __init__(self, *args, **kwargs):		
		self.base_fields['theFile']=ExtFileField(ext_whitelist=(".pdf",".jpg",".jpeg",))
		super(UploadForm, self).__init__(*args, **kwargs)

	class Meta:
		model = UploadedFile
		fields = ['theFile',]


class ApplicationForm(ModelForm):
	class Meta:
		model = Application
		fields = ['fellowship','fullName','email','phone',"cv","portrait","reference_1","reference_2","reference_3","letter_of_intent"]

# class ApplicationForm(ModelForm):
# 	def __init__(self, *args, **kwargs):
# 		super(ApplicationForm, self).__init__(*args, **kwargs)

# 	class Meta:
# 		model = Application
# 		fields = ['fullName','email','phone','statement',"cv","portrait","reference_1","reference_2","reference_3"]

application/form/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from form import models
from django.template.context_processors import csrf
import os, datetime,json
from form import forms

def home(request):
	print request.method
	if request.method == 'POST':
		# print request.POST
		# print request.FILES
		if request.POST.get("fullName"):
			form = forms.ApplicationForm(request.POST, request.FILES)
			if form.is_valid():
				outCome = form.save()
				return HttpResponse("it worked")
			return HttpResponse(form.errors.as_json(),content_type='application/json',status="400",reason="application didn't work")
		elif request.FILES:
			form = forms.UploadForm(request.POST, request.FILES)
			if form.is_valid():
				outCome = form.save()
				return HttpResponse(outCome.pk)
			return HttpResponse(form.errors.as_json(),content_type='application/json',status="400",reason="something wrong with the form")
		else :
			return HttpResponse(json.dumps({"theFile": [{"message": "This field cannot be empty", "code": ""}]}),content_type='application/json',status="400",reason="you need to submit something")
		
	form = forms.ApplicationForm()
	return render(request, 'regform.html', { "form":form })

def success(request):
	return HttpResponse("it worked")

application/templates/base.html
{% load staticfiles %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" class="">
<head>
	<meta charset="utf-8">
	<meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
	<meta content="width=device-width, initial-scale=1.0, minimum-scale=1.0,maximum-scale=10.0,user-scalable=no" name="viewport">

	<link rel="stylesheet" type="text/css" href="{% static "css/style.min.css"%}">
	<title>{% block pageName %}Sickkids Orthopaedic Surgery Application{% endblock pageName %}</title>
	<script src="//use.typekit.net/whd6btz.js"></script>
	<script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body>

	<div id="wrapper">
		{% block content %}
			
		{% endblock content %}
	</div>

	{% block script %}
		<script type="text/javascript" src="{% static "js/lib/jquery.min.js"%}"></script>
		<script type="text/javascript" src="{% static "js/script.js"%}"></script>
		<script type="text/javascript" src="{% static "js/lib/jquery.form.min.js" %}"></script>
		<script type="text/javascript">
			app.init();
			// $("#yes_na").click();
		</script>
	{% endblock script %}	
</body>
</html>

application/templates/post-regform.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	
<h2>Thank you for your application.</h2>
		
{% endblock content %}	

{% block script %}
		
{% endblock script %}	

application/templates/regform.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
	

<div id="wrapper">

	<noscript>
		<h1>YOU NEED javascript enabled to complete this form, please enable it or use a modern browser.</h1>
	</noscript>


	<div id="first_selection">
		<h2>SickKids Orthopaedic Fellowship</h2>
		<hr></hr>
		<p>Did you complete your residency training from a North American Institution?</p>
		<button id="yes_na" aria-label="No I did not completed my residency in North American">no</button><button aria-label="Yes I completed my residency in North American" id="no_na">yes</button>
	</div>
	<div id="no_study_in_canada" class="hidden">
		<h2>SickKids Orthopaedic Fellowship</h2>
		<hr></hr>
		<p>
			Please apply through SF Match: <a href="https://www.sfmatch.org/" target="_blank">www.sfmatch.org</a>
		</p>
	</div>
	<div id="study_in_canada" class="hidden">
		<h2>SickKids Orthopaedic Fellowship Application Form</h2>
		<hr></hr>
		<form action"/" method="post" enctype="multipart/form-data" id="main-form">
			{% csrf_token %}
			<div id="fellowship-form">
				<label for="id_fellowship">Select Fellowship</label>
				<div class="error_onsend"></div>
				<select id="id_fellowship" name="fellowship"> 
					<option value="paediatric">Paediatric</option>
					<option value="spine">Spine</option>
					<option value="trans-canada">Trans-Canada</option>
				</select>
			</div>

			<h3>Personal Information</h3>

			<div id="fullName-form">
					<label for="id_fullName">Full Name</label>
					<div class="error_field"></div>
					<input id="id_fullName" spellcheck="false" placeholder="John Doe" name="fullName" type="text">
			</div>
			<div id="email-form">
					<label for="id_email">Email</label>
					<div class="error_field"></div>
					<input id="id_email" spellcheck="false" placeholder="example@gmail.com" name="email" type="email">
			</div>
			<div id="phone-form">
					<label for="id_phone">Phone</label>
					<div class="error_field"></div>
					<input id="id_phone" spellcheck="false" placeholder="+1 (416) 813–6686" name="phone" type="tel">
			</div>

			<input id="id_cv" name="cv" type="hidden">
		
			<input id="id_portrait" name="portrait" type="hidden">
		
			<input id="id_reference_1" name="reference_1" type="hidden">
		
			<input id="id_reference_2" name="reference_2" type="hidden">
		
			<input id="id_reference_3" name="reference_3" type="hidden">

			<input id="id_letter_of_intent" name="letter_of_intent" type="hidden">
			<noscript>
				<input type="submit" value="submit">
			</noscript>

		</form>

		<form action"/" method="post" id="cv-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number" name="pk" value="-1"></input>
			<label for="theFile_cv">CV <small>only submit .pdf file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_cv" type="file" name="theFile"></input>
		</form>
		<form action"/" method="post" id="portrait-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number"></input>
			<label for="theFile_portrait">Portrait <small>only submit .jpg file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_portrait" type="file" name="theFile"></input>
		</form>

		<form action"/" method="post" id="letter_of_intent-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number" name="pk" value="-1"></input>
			<label for="theFile_letter_of_intent">Letter of intent <small>only submit .pdf file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_letter_of_intent" type="file" name="theFile"></input>
		</form>		
		<h3>References</h3>
		<form action"/" method="post" id="reference_1-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number"></input>
			<label for="theFile_reference_1">Attach reference letter 1 <small>only submit .pdf file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_reference_1" type="file" name="theFile"></input>
		</form>	
		<form action"/" method="post" id="reference_2-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number"></input>
			<label for="theFile_reference_2">Attach reference letter 2 <small>only submit .pdf file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_reference_2" type="file" name="theFile"></input>
		</form>
		<form action"/" method="post" id="reference_3-form" enctype="multipart/form-data">
			{% csrf_token %}
			<input class="pknumber" type="number"></input>
			<label for="theFile_reference_3">Attach reference letter 3 <small>only submit .pdf file type</small></label>
			<div class="error_field"></div>
			<input id="theFile_reference_3" type="file" name="theFile"></input>
		</form>
		<button id="submit_everything">Submit Application</button>
	</div>
	<div class="overlay" id="loading_form">
		<div>
			<h2>Saving your application... this may take 10-30 seconds</h2>
		</div>
	</div>
	<div class="overlay" id="loaded_form">
		<div>
			<h2>
				Your application has been submitted thank you. <br>
				Read more about the fellowship at <a href="http://sickkidsorthofellowship.ca/">SickKids Orthopaedic Fellowship</a>.
			</h2>
		</div>
	</div>	
</div>

{% endblock content %}